# Site settings
title: Human Rights Initiative at the University at Buffalo
email: admin@hribuffalo.org
description: Human Rights Initiative
baseurl: ""
url: "http://HRIBuffalo.org"
#twitter_username:
#github_username:

# Build settings
markdown: kramdown
